export const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";
export const VIEW_CURRENT_POST = "VIEW_CURRENT_POST";
export const REMOVE_BACKDROP = "REMOVE_BACKDROP";
export const SET_LOADING = "SET_LOADING";
export const INIT_POSTS = "INIT_POSTS";
export const SET_POSTS = "SET_POSTS";
export const FAILED_FETCHING_POSTS = "FAILED_FETCHING_POSTS";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_FAIL = "NEW_POST_FAIL";
export const NEW_POST_START = "NEW_POST_START";
export const NEW_POST_INIT = "NEW_POST_INIT";

export const GET_FULL_POST = "GET_FULL_POST";
export const GET_FULL_POST_SUCCESS = "GET_FULL_POST_SUCCESS";
export const GET_FULL_POST_FAILED = "GET_FULL_POST_FAILED";

export const ADD_TAG = "ADD_TAG";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const ADD_TAG_FAILED = "ADD_TAG_FAILED";
export const TOGGLE_TAG_MODE = "TOGGLE_TAG_MODE";
export const ONCHANGE_TAG_HANDLER = "ONCHANGE_TAG_HANDLER";
