export const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";
export const VIEW_CURRENT_POST = "VIEW_CURRENT_POST";
export const REMOVE_BACKDROP = "REMOVE_BACKDROP";
export const INIT_POSTS = "INIT_POSTS";
export const SET_POSTS = "SET_POSTS";
export const FAILED_FETCHING_POSTS = "FAILED_FETCHING_POSTS";
